name: Run all scripts every 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"   # svakih 5 minuta
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run single scraping cycle
        run: python run_all.py

      - name: Commit & push new results
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add .
          git commit -m "auto: run_all update $(date '+%Y-%m-%d %H:%M')" || echo "No changes"
          git push
