name: Run all scripts continuously (1min pause, auto-reset every 3h, silent git)

on:
  schedule:
    - cron: "0 */3 * * *"  # automatski restart svakih 3h
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 180  # maksimalno trajanje jedne sesije = 3h

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Continuous execution (run → commit → wait → repeat)
        run: |
          git config --global user.name "GitHub Action" >/dev/null 2>&1
          git config --global user.email "actions@github.com" >/dev/null 2>&1

          while true; do
            echo "=== [$(date)] Starting run_all.py ==="
            python run_all.py

            echo "=== [$(date)] Finished run_all.py, committing changes... ==="
            git add . >/dev/null 2>&1
            git commit -m "auto: run_all update $(date '+%Y-%m-%d %H:%M')" >/dev/null 2>&1 || true

            # tiha sinhronizacija sa origin/main
            git pull --rebase origin main >/dev/null 2>&1 || true
            git push origin main >/dev/null 2>&1 || echo "[git] Push skipped (no changes or race condition)"

            echo "=== [$(date)] Sleeping 1 minute before next cycle... ==="
            sleep 60
          done
