name: Run all scripts continuously (1min pause, auto-reset every 3h, auto-push after each cycle)

on:
  schedule:
    - cron: "0 */3 * * *"  # automatski restart svakih 3 sata
  workflow_dispatch:        # ručno pokretanje iz GitHub Actions taba

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 180  # maksimalno trajanje jedne sesije = 3h

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Continuous execution (run → commit → wait → repeat)
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"

          while true; do
            echo "=== [$(date)] Starting run_all.py ==="
            python run_all.py

            echo "=== [$(date)] Finished run_all.py, committing changes... ==="
            git add .
            git commit -m "auto: run_all update $(date '+%Y-%m-%d %H:%M')" || echo "No changes"
            git push || echo "Push failed (maybe no new data)"

            echo "=== [$(date)] Sleeping 1 minute before next cycle... ==="
            sleep 60
          done
